sudo: required
services:
  - docker

before_install:
  - docker build -t mynameiskingsleyn/docker-react2 -f Dockerfile.dev .


script:
  - docker run mynameiskingsleyn/docker-react2 npm run test -- --coverage
